package com.objectstyle.lm_demo.cayenne.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.objectstyle.lm_demo.cayenne.WGameEvent;
import com.objectstyle.lm_demo.cayenne.WTeam;

/**
 * Class _WGame was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WGame extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ARENA = new Property<String>("arena");
    public static final Property<Integer> AWAY_SCORE = new Property<Integer>("awayScore");
    public static final Property<Date> DATE_TIME = new Property<Date>("dateTime");
    public static final Property<Integer> HOME_SCORE = new Property<Integer>("homeScore");
    public static final Property<List<WGameEvent>> GAME_EVENTS = new Property<List<WGameEvent>>("gameEvents");
    public static final Property<WTeam> HOME_TEAM = new Property<WTeam>("homeTeam");
    public static final Property<WTeam> VISITING_TEAM = new Property<WTeam>("visitingTeam");

    public void setArena(String arena) {
        writeProperty("arena", arena);
    }
    public String getArena() {
        return (String)readProperty("arena");
    }

    public void setAwayScore(Integer awayScore) {
        writeProperty("awayScore", awayScore);
    }
    public Integer getAwayScore() {
        return (Integer)readProperty("awayScore");
    }

    public void setDateTime(Date dateTime) {
        writeProperty("dateTime", dateTime);
    }
    public Date getDateTime() {
        return (Date)readProperty("dateTime");
    }

    public void setHomeScore(Integer homeScore) {
        writeProperty("homeScore", homeScore);
    }
    public Integer getHomeScore() {
        return (Integer)readProperty("homeScore");
    }

    public void addToGameEvents(WGameEvent obj) {
        addToManyTarget("gameEvents", obj, true);
    }
    public void removeFromGameEvents(WGameEvent obj) {
        removeToManyTarget("gameEvents", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WGameEvent> getGameEvents() {
        return (List<WGameEvent>)readProperty("gameEvents");
    }


    public void setHomeTeam(WTeam homeTeam) {
        setToOneTarget("homeTeam", homeTeam, true);
    }

    public WTeam getHomeTeam() {
        return (WTeam)readProperty("homeTeam");
    }


    public void setVisitingTeam(WTeam visitingTeam) {
        setToOneTarget("visitingTeam", visitingTeam, true);
    }

    public WTeam getVisitingTeam() {
        return (WTeam)readProperty("visitingTeam");
    }


}
