package com.objectstyle.lm_demo.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.objectstyle.lm_demo.cayenne.WGame;

/**
 * Class _WGameEvent was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WGameEvent extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> PERIOD = new Property<Integer>("period");
    public static final Property<String> TIME_IN_PERIOD = new Property<String>("timeInPeriod");
    public static final Property<String> TYPE = new Property<String>("type");
    public static final Property<WGame> GAME = new Property<WGame>("game");

    public void setPeriod(Integer period) {
        writeProperty("period", period);
    }
    public Integer getPeriod() {
        return (Integer)readProperty("period");
    }

    public void setTimeInPeriod(String timeInPeriod) {
        writeProperty("timeInPeriod", timeInPeriod);
    }
    public String getTimeInPeriod() {
        return (String)readProperty("timeInPeriod");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void setGame(WGame game) {
        setToOneTarget("game", game, true);
    }

    public WGame getGame() {
        return (WGame)readProperty("game");
    }


}
