package com.objectstyle.lm_demo.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.objectstyle.lm_demo.cayenne.WGame;

/**
 * Class _WTeam was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WTeam extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<List<WGame>> W_GAMES = new Property<List<WGame>>("wGames");
    public static final Property<List<WGame>> W_GAMES1 = new Property<List<WGame>>("wGames1");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToWGames(WGame obj) {
        addToManyTarget("wGames", obj, true);
    }
    public void removeFromWGames(WGame obj) {
        removeToManyTarget("wGames", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WGame> getWGames() {
        return (List<WGame>)readProperty("wGames");
    }


    public void addToWGames1(WGame obj) {
        addToManyTarget("wGames1", obj, true);
    }
    public void removeFromWGames1(WGame obj) {
        removeToManyTarget("wGames1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WGame> getWGames1() {
        return (List<WGame>)readProperty("wGames1");
    }


}
